### ISSUE TITLE
Incorrect links to blog pages after translating

### ISSUE THREAD

**Issue by FrediKats** [yegor256/jekyll-chatgpt-translate#38]
Problem pages samples:
- https://www.yegor256.com/ru/2014/11/24/principles-of-bug-tracking.html
- https://www.yegor256.com/ru/2015/01/08/morning-standup-meetings.html

Step to repro:
- Open translated page
- Find link to another blog page

Expected behavior:
Link has href to another blog page

Actual behavior:
LInk has href to itself

Additional info:
Links to wiki and other external resources are correct.

---

More details:

Source: https://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

"discourage" has link to  https://www.yegor256.com/2014/10/07/stop-chatting-start-coding.html

Translated: https://www.yegor256.com/ru/2014/11/24/principles-of-bug-tracking.html

"отговариваемся " has link to https://www.yegor256.com/ru/2014/11/24/principles-of-bug-tracking.html (page itself)
"электронная почта" also has link to page itself

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.31`
